# noinspection YAMLSchemaValidation
name: ${baseCoordinates}
main: eu.xap3y.gungame.GunGame
version: ${version}
api-version: '1.20'
description: GunGame minigame
loader: eu.xap3y.gungame.GunGameLoader
has-open-classloader: false

author: XAP3Y
website: https://pvpcraft.cz

load: POSTWORLD

dependencies:
    server:
        Vault:
            required: true
        PlaceholderAPI:
            required: false
        Multiverse-Core:
            required: false
        LiteEco:
            required: false